# Generated by Django 4.2.6 on 2023-10-23 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='grupimg/%Y/%m/%d')),
                ('data_incricao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('titulo', models.CharField(max_length=180)),
                ('descricaoshort', models.TextField()),
                ('descricao', models.TextField()),
                ('escola', models.CharField(max_length=180)),
                ('tutor', models.CharField(max_length=180)),
                ('integrantes', models.TextField()),
            ],
        ),
    ]
