# Generated by Django 4.2.6 on 2023-10-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdevotacao', '0002_turmas_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas',
            name='votos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
