# Generated by Django 4.2.6 on 2023-10-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdevotacao', '0003_alter_turmas_votos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='descricaoshort',
        ),
        migrations.AlterField(
            model_name='turmas',
            name='descricao',
            field=models.TextField(max_length=600),
        ),
    ]
